macro(GetInformations)
  print("Informations:")
  print("  Project [${PROJECT_NAME} ${PROJECT_VERSION}]")
  print("  Brief [${PROJECT_BRIEF}]")
  print("  Author [${PROJECT_AUTHOR}]")
  print("  CMake version [${CMAKE_VERSION}]")
  print("  System [${CMAKE_SYSTEM}]")
  print("  Compiler [${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}]")
  print("  Build type [${CMAKE_BUILD_TYPE}]")
  print("  Debug postfix [${CMAKE_DEBUG_POSTFIX}]")
  if (UNIX)
    print("  Code coverage [${ENABLE_COVERAGE}]")
  else()
    print("  Code coverage [NOT AVAIBLE]")
  endif()
  if (UNIX)
    print("  Google Address Sanitizer [${ENABLE_ASAN}]")
  else()
    print("  Google Address Sanitizer [NOT AVAIBLE]")
  endif()
  if (UNIX)
    print("  Google Undefined Sanitizer [${ENABLE_USAN}]")
  else()
    print("  Google Undefined Sanitizer [NOT AVAIBLE]")
  endif()
  if (UNIX)
    print("  Google Thread Sanitizer [${ENABLE_TSAN}]")
  else()
    print("  Google Thread Sanitizer [NOT AVAIBLE]")
  endif()
  print("  Install prefix [${CMAKE_INSTALL_PREFIX}]")
  print("  Output path [${EXECUTABLE_OUTPUT_PATH}]")
  print("  Executable extension [${EXECUTABLE_EXTENSION}]")
endmacro()