set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(call_stack REQUIRED)
#find_package(CURL REQUIRED)
#find_package(easywsclient REQUIRED)
find_package(GTest REQUIRED)
find_package(JPEG REQUIRED)
find_package(PNG REQUIRED)
find_package(Rs232 REQUIRED)
find_package(Threads REQUIRED)
find_package(ZLIB REQUIRED)

if(MSVC)
  set(SWITCH_GUI WIN32)
  set(STANDARD_CORE_LINK_LIBRARIES ws2_32 iphlpapi rpcrt4)    
  set(STANDARD_GRAPHIC_LINK_LIBRARIES uxtheme comctl32)
elseif (APPLE)
  set(SWITCH_GUI MACOSX_BUNDLE)
  set(STANDARD_CORE_LINK_LIBRARIES dl ncurses)	
  set(STANDARD_GRAPHIC_LINK_LIBRARIES )
  set(COCOA_FRAMEWORK "-framework Carbon -framework Cocoa -framework ApplicationServices -framework Foundation")
elseif(UNIX)
  find_package(PkgConfig)
  pkg_check_modules(GTKMM gtkmm-3.0)
  if(NOT GTKMM_FOUND)
    message(FATAL_ERROR "gtkmm-3.0 not found!")
  endif()
  include_directories(${GTKMM_INCLUDE_DIRS})
  link_directories(${GTKMM_LIBRARY_DIRS})
  set(SWITCH_GUI)
  set(STANDARD_CORE_LINK_LIBRARIES dl rt uuid)
  set(STANDARD_GRAPHIC_LINK_LIBRARIES ${GTKMM_LIBRARIES})
endif ()	
