/// @page ExternalProductsandLibrariesPage External Products and Libraries
/// The external products and libraries included in Pcf.
///
/// List:
/// | Prodcut     | Copyright                                                                                                              | Desciption                                                                                    | Release |
/// |-------------|------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|---------|
/// | call_stack  | Fredrik Orderud                                                                                                        | Provides information about the call stack                                                     |         |
/// | cmake       | Kitware, Inc., Insight Software Consortium                                                                             | Cross Platform Makefile Generator                                                             | 2.8.11  |
/// | Doxygen     | Dimitri van Heesch                                                                                                     | Documentation generator                                                                       | 1.8.6   |
/// | Fl_DragBar  | <unknown>                                                                                                              | Provides dragbar on fltk                                                                      |         |
/// | Fl_Gel_Tabs | Greg Ercolano                                                                                                          | Provides Aple's Aqua look tabs                                                                |         |
/// | FLTK        | Fabien Costantini, Greg Ercolano, Manolo Gouy, Ian MacArthur, Matthias Melcher, Pierre Ossman, Albrecht Schlosser, ... | Fast Light Tool Kit                                                                           | 1.3.3   |
/// | gel_button  | <unknown>                                                                                                              | Provides Apple's Aqua look button                                                             |         |
/// | gtest       | Google                                                                                                                 | Google C++ Testing Framework                                                                  | 1.7.0   |
/// | icu         | IBM                                                                                                                    | International Components for Unicode                                                          | 52      |
/// | jpeglib     | The Independent JPEG Group's JPEG software                                                                             | This package contains C software to implement JPEG image encoding, decoding, and transcoding. | 8c      |
/// | libcurl     | Daniel Stenberg                                                                                                        | the multiprotocol file transfer library                                                       | 7.32.0  |
/// | StackWalker | Jochen Kalmbach                                                                                                        | Walking the callstack                                                                         | v5      |
/// | Zlib        | Jean-loup Gailly (compression) and Mark Adler (decompression)                                                          | A Massively Spiffy Yet Delicately Unobtrusive Compression Library                             | 1.2.8   |
