#pragma once

#undef AddForm
#undef CreateDirectory
#undef GetCurrentDirectory
#undef GetDriveType
#undef GetEnvironmentVariable
#undef GetFileAttributes
#undef GetLogicalDriveStrings
#undef GetTempPath
#undef GetUserName
#undef GetVolumeInformation
#undef GetWindowText
#undef major
#undef max
#undef minor
#undef MemoryBarrier
#undef None
#undef RemoveDirectory
#undef SetCurrentDirectory
#undef SetEnvironmentVariable
#undef SetVolumeLabel
#undef Yield
