find_package(Threads REQUIRED)
find_package(call_stack REQUIRED)
find_package(CURL REQUIRED)
find_package(easywsclient REQUIRED)
find_package(Rs232 REQUIRED)
find_package(ZLIB REQUIRED)
find_package(JPEG REQUIRED)
find_package(PNG REQUIRED)
find_package(GTest REQUIRED)

if (APPLE)
  set(PCF_GUI MACOSX_BUNDLE)
  set(STANDARD_CORE_LINK_LIBRARIES dl)	
  set(STANDARD_GRAPHIC_LINK_LIBRARIES "-framework Cocoa -framework Foundation")
elseif(UNIX)
  set(PCF_GUI)
  find_package(FLTK REQUIRED)
  set(STANDARD_CORE_LINK_LIBRARIES dl rt uuid)
  set(STANDARD_GRAPHIC_LINK_LIBRARIES ${FLTK_LIBRARIES})
elseif(MSVC)
  set(PCF_GUI WIN32)
  set(STANDARD_CORE_LINK_LIBRARIES Ws2_32.lib Iphlpapi.lib Rpcrt4.lib)    
  set(STANDARD_GRAPHIC_LINK_LIBRARIES Uxtheme)
endif ()	
