find_package(Threads REQUIRED)
find_package(call_stack REQUIRED)
find_package(CURL REQUIRED)
find_package(easywsclient REQUIRED)
find_package(Rs232 REQUIRED)
find_package(ZLIB REQUIRED)
find_package(JPEG REQUIRED)
find_package(PNG REQUIRED)
find_package(GTest REQUIRED)
find_package(FLTK REQUIRED)

message("--------> gtkmm = ${GTKMM_LIBRARIES}")

if (APPLE)
  set(PCF_GUI MACOSX_BUNDLE)
  set(STANDARD_CORE_LINK_LIBRARIES dl)	
  set(STANDARD_GRAPHIC_LINK_LIBRARIES "-framework Cocoa -framework Foundation fltk_images fltk")
elseif(UNIX)
  set(PCF_GUI)
  find_package(PkgConfig)
  pkg_check_modules(GTKMM gtkmm-3.0)
  if(NOT GTKMM_FOUND)
      message(FATAL_ERROR "gtkmm-3.0 not found!")
  endif()
  link_directories(${GTKMM_LIBRARY_DIRS})
  include_directories(${GTKMM_INCLUDE_DIRS})
  set(STANDARD_CORE_LINK_LIBRARIES dl rt uuid)
  set(STANDARD_GRAPHIC_LINK_LIBRARIES ${GTKMM_LIBRARIES} fltk_images fltk)
elseif(MSVC)
  set(PCF_GUI WIN32)
  set(STANDARD_CORE_LINK_LIBRARIES Ws2_32.lib Iphlpapi.lib Rpcrt4.lib)    
  set(STANDARD_GRAPHIC_LINK_LIBRARIES Uxtheme fltk_images fltk)
endif ()	
