// generated by Fast Light User Interface Designer (fluid) version 1.0010

#include "demoDragBar.h"
#include "Fl_DragBar.H"

Fl_Double_Window *win=(Fl_Double_Window *)0;

static void cb_X(Fl_Button*, void*) {
  win->hide();
}

Fl_Scroll *scroll=(Fl_Scroll *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = win = new Fl_Double_Window(303, 232);
    w = o;
    { Fl_DragBar* o = new Fl_DragBar(18, 0, 284, 16, "Window title");
      o->box(FL_THIN_UP_BOX);
      o->labelsize(12);
      o->type(Fl_DragBar::NICEWINDRAG);
    }
    { Fl_Button* o = new Fl_Button(0, 0, 18, 16, "X");
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(10);
      o->callback((Fl_Callback*)cb_X);
    }
    { Fl_Scroll* o = scroll = new Fl_Scroll(20, 42, 260, 176);
      o->box(FL_DOWN_BOX);
      o->color(215);
      { Fl_Group* o = new Fl_Group(32, 106, 224, 98);
        o->box(FL_ENGRAVED_BOX);
        o->color(52);
        { Fl_DragBar* o = new Fl_DragBar(34, 108, 16, 94, "widget bar");
          o->box(FL_THIN_UP_BOX);
          o->labelsize(12);
          o->type(Fl_DragBar::NICEFLDRAG);
        }
        new Fl_Button(78, 144, 78, 30, "A button");
        new Fl_Dial(186, 140, 54, 50);
        o->end();
      }
      o->end();
    }
    o->clear_border();
    o->end();
  }
  return w;
}

int main(int ac,char **av) {
  make_window()->show();
Fl::run();
}
