// generated by Fast Light User Interface Designer (fluid) version 1.0010

#ifndef demoDragBar_h
#define demoDragBar_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win;
#include <FL/Fl_Button.H>
#include <FL/Fl_Scroll.H>
extern Fl_Scroll *scroll;
#include <FL/Fl_Group.H>
#include <FL/Fl_Dial.H>
Fl_Double_Window* make_window();
int main(int ac,char **av);
#endif
