var searchData=
[
  ['samesizetupleprefixcomparator',['SameSizeTuplePrefixComparator',['../structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator.html',1,'std::tr1::gtest_internal']]],
  ['samesizetupleprefixcomparator_3c_200_2c_200_20_3e',['SameSizeTuplePrefixComparator&lt; 0, 0 &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_010_00_010_01_4.html',1,'std::tr1::gtest_internal']]],
  ['samesizetupleprefixcomparator_3c_20k_2c_20k_20_3e',['SameSizeTuplePrefixComparator&lt; k, k &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_01k_00_01k_01_4.html',1,'std::tr1::gtest_internal']]],
  ['sbyte',['SByte',['../struct_pcf_1_1_system_1_1_s_byte.html',1,'Pcf::System']]],
  ['scoped_5fptr',['scoped_ptr',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20_3a_3astd_3a_3astring_20_3e',['scoped_ptr&lt; ::std::string &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20_3a_3astd_3a_3astringstream_20_3e',['scoped_ptr&lt; ::std::stringstream &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20const_20_3a_3astd_3a_3astring_20_3e',['scoped_ptr&lt; const ::std::string &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20const_20t_20_3e',['scoped_ptr&lt; const T &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20testing_3a_3ainternal_3a_3aparamiteratorinterface_3c_20t_20_3e_20_3e',['scoped_ptr&lt; testing::internal::ParamIteratorInterface&lt; T &gt; &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20testing_3a_3ainternal_3a_3atestmetafactorybase_3c_20paramtype_20_3e_20_3e',['scoped_ptr&lt; testing::internal::TestMetaFactoryBase&lt; ParamType &gt; &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scopedfaketestpartresultreporter',['ScopedFakeTestPartResultReporter',['../classtesting_1_1_scoped_fake_test_part_result_reporter.html',1,'testing']]],
  ['scopedtrace',['ScopedTrace',['../classtesting_1_1internal_1_1_scoped_trace.html',1,'testing::internal']]],
  ['scrollablecontrol',['ScrollableControl',['../class_pcf_1_1_system_1_1_windows_1_1_forms_1_1_scrollable_control.html',1,'Pcf::System::Windows::Forms']]],
  ['securestring',['SecureString',['../class_pcf_1_1_system_1_1_security_1_1_secure_string.html',1,'Pcf::System::Security']]],
  ['security',['Security',['../class_____o_s_1_1_core_api_1_1_security.html',1,'__OS::CoreApi']]],
  ['securityexception',['SecurityException',['../class_pcf_1_1_system_1_1_security_1_1_security_exception.html',1,'Pcf::System::Security']]],
  ['semaphore',['Semaphore',['../class_pcf_1_1_system_1_1_threading_1_1_semaphore.html',1,'Pcf::System::Threading']]],
  ['semaphorefullexception',['SemaphoreFullException',['../class_pcf_1_1_system_1_1_threading_1_1_semaphore_full_exception.html',1,'Pcf::System::Threading']]],
  ['serialdatareceivedeventargs',['SerialDataReceivedEventArgs',['../class_pcf_1_1_system_1_1_i_o_1_1_ports_1_1_serial_data_received_event_args.html',1,'Pcf::System::IO::Ports']]],
  ['serialerrorreceivedeventargs',['SerialErrorReceivedEventArgs',['../class_pcf_1_1_system_1_1_i_o_1_1_ports_1_1_serial_error_received_event_args.html',1,'Pcf::System::IO::Ports']]],
  ['serializationexception',['SerializationException',['../class_pcf_1_1_system_1_1_runtime_1_1_serialization_1_1_serialization_exception.html',1,'Pcf::System::Runtime::Serialization']]],
  ['serializationinfo',['SerializationInfo',['../class_pcf_1_1_system_1_1_runtime_1_1_serialization_1_1_serialization_info.html',1,'Pcf::System::Runtime::Serialization']]],
  ['serialpinchangedeventargs',['SerialPinChangedEventArgs',['../class_pcf_1_1_system_1_1_i_o_1_1_ports_1_1_serial_pin_changed_event_args.html',1,'Pcf::System::IO::Ports']]],
  ['serialport',['SerialPort',['../class_pcf_1_1_system_1_1_i_o_1_1_ports_1_1_serial_port.html',1,'Pcf::System::IO::Ports']]],
  ['sessionhandle',['SessionHandle',['../struct_session_handle.html',1,'']]],
  ['sharedpointer',['SharedPointer',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20barrierdata_20_3e',['SharedPointer&lt; BarrierData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20bool_20_3e',['SharedPointer&lt; bool &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20callstack_20_3e',['SharedPointer&lt; CallStack &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20defaulttracelistenerdata_20_3e',['SharedPointer&lt; DefaultTraceListenerData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20eventresetmode_20_3e',['SharedPointer&lt; EventResetMode &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20filestreamdata_20_3e',['SharedPointer&lt; FileStreamData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20fontdata_20_3e',['SharedPointer&lt; FontData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20fontfamilydata_20_3e',['SharedPointer&lt; FontFamilyData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20int32_5ft_20_3e',['SharedPointer&lt; int32_t &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20memorystreamdata_20_3e',['SharedPointer&lt; MemoryStreamData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20networkstreamdata_20_3e',['SharedPointer&lt; NetworkStreamData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20pcf_3a_3asystem_3a_3acollections_3a_3ageneric_3a_3aicomparer_3c_20int32_5ft_20_3e_20_3e',['SharedPointer&lt; Pcf::System::Collections::Generic::IComparer&lt; int32_t &gt; &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20pcf_3a_3asystem_3a_3acollections_3a_3ageneric_3a_3aicomparer_3c_20int64_5ft_20_3e_20_3e',['SharedPointer&lt; Pcf::System::Collections::Generic::IComparer&lt; int64_t &gt; &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20pcf_3a_3asystem_3a_3acollections_3a_3ageneric_3a_3aicomparer_3c_20pcf_3a_3asystem_3a_3astring_20_3e_20_3e',['SharedPointer&lt; Pcf::System::Collections::Generic::IComparer&lt; Pcf::System::String &gt; &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20pcf_3a_3asystem_3a_3acollections_3a_3ageneric_3a_3aicomparer_3c_20string_20_3e_20_3e',['SharedPointer&lt; Pcf::System::Collections::Generic::IComparer&lt; String &gt; &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20pcf_3a_3asystem_3a_3acollections_3a_3ageneric_3a_3aicomparer_3c_20system_3a_3astring_20_3e_20_3e',['SharedPointer&lt; Pcf::System::Collections::Generic::IComparer&lt; System::String &gt; &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20pcf_3a_3asystem_3a_3acollections_3a_3ageneric_3a_3aicomparer_3c_20t_20_3e_20_3e',['SharedPointer&lt; Pcf::System::Collections::Generic::IComparer&lt; T &gt; &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20pcf_3a_3asystem_3a_3acollections_3a_3ageneric_3a_3aicomparer_3c_20tkey_20_3e_20_3e',['SharedPointer&lt; Pcf::System::Collections::Generic::IComparer&lt; TKey &gt; &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20pcf_3a_3asystem_3a_3acollections_3a_3ageneric_3a_3aienumerator_3c_20t_20_3e_20_3e',['SharedPointer&lt; Pcf::System::Collections::Generic::IEnumerator&lt; T &gt; &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20pcf_3a_3asystem_3a_3acollections_3a_3ageneric_3a_3akeyvaluepair_20_3e',['SharedPointer&lt; Pcf::System::Collections::Generic::KeyValuePair &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20pcf_3a_3asystem_3a_3adiagnostics_3a_3astackframe_20_3e',['SharedPointer&lt; Pcf::System::Diagnostics::StackFrame &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20pcf_3a_3asystem_3a_3adiagnostics_3a_3atracelistener_20_3e',['SharedPointer&lt; Pcf::System::Diagnostics::TraceListener &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20pcf_3a_3asystem_3a_3aexception_20_3e',['SharedPointer&lt; Pcf::System::Exception &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20pcf_3a_3asystem_3a_3aio_3a_3astream_20_3e',['SharedPointer&lt; Pcf::System::IO::Stream &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20pcf_3a_3asystem_3a_3anet_3a_3asockets_3a_3asocket_20_3e',['SharedPointer&lt; Pcf::System::Net::Sockets::Socket &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20pcf_3a_3asystem_3a_3aobject_20_3e',['SharedPointer&lt; Pcf::System::Object &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20pcf_3a_3asystem_3a_3astring_20_3e',['SharedPointer&lt; Pcf::System::String &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20processdata_20_3e',['SharedPointer&lt; ProcessData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20processstartinfodata_20_3e',['SharedPointer&lt; ProcessStartInfoData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20registryhandle_20_3e',['SharedPointer&lt; RegistryHandle &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20socketdata_20_3e',['SharedPointer&lt; SocketData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20std_3a_3acondition_5fvariable_20_3e',['SharedPointer&lt; std::condition_variable &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20std_3a_3amutex_20_3e',['SharedPointer&lt; std::mutex &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20std_3a_3arecursive_5ftimed_5fmutex_20_3e',['SharedPointer&lt; std::recursive_timed_mutex &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20std_3a_3aset_3c_20t_2c_20setcomparer_2c_20tallocator_20_3e_20_3e',['SharedPointer&lt; std::set&lt; T, SetComparer, TAllocator &gt; &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20streamwriterdata_20_3e',['SharedPointer&lt; StreamWriterData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20stringwriterdata_20_3e',['SharedPointer&lt; StringWriterData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20system_3a_3aio_3a_3astream_20_3e',['SharedPointer&lt; System::IO::Stream &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20system_3a_3aio_3a_3astreamwriter_20_3e',['SharedPointer&lt; System::IO::StreamWriter &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20system_3a_3aio_3a_3atextwriter_20_3e',['SharedPointer&lt; System::IO::TextWriter &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20system_3a_3atext_3a_3aencoding_20_3e',['SharedPointer&lt; System::Text::Encoding &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20taskdata_20_3e',['SharedPointer&lt; TaskData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20tcpclientdata_20_3e',['SharedPointer&lt; TcpClientData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20tcplistenerdata_20_3e',['SharedPointer&lt; TcpListenerData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20threaditem_20_3e',['SharedPointer&lt; ThreadItem &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20timerdata_20_3e',['SharedPointer&lt; TimerData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20tracelistenerdata_20_3e',['SharedPointer&lt; TraceListenerData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20tracesourcedata_20_3e',['SharedPointer&lt; TraceSourceData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['sharedpointer_3c_20webrequeststreamdata_20_3e',['SharedPointer&lt; WebRequestStreamData &gt;',['../class_pcf_1_1_shared_pointer.html',1,'Pcf']]],
  ['single',['Single',['../struct_pcf_1_1_system_1_1_single.html',1,'Pcf::System']]],
  ['singlefailurechecker',['SingleFailureChecker',['../classtesting_1_1internal_1_1_single_failure_checker.html',1,'testing::internal']]],
  ['singlerequest',['SingleRequest',['../struct_single_request.html',1,'']]],
  ['size',['Size',['../class_pcf_1_1_system_1_1_drawing_1_1_size.html',1,'Pcf::System::Drawing']]],
  ['sizef',['SizeF',['../class_pcf_1_1_system_1_1_drawing_1_1_size_f.html',1,'Pcf::System::Drawing']]],
  ['smtp',['SMTP',['../struct_s_m_t_p.html',1,'']]],
  ['smtp_5fconn',['smtp_conn',['../structsmtp__conn.html',1,'']]],
  ['socket',['Socket',['../class_pcf_1_1_system_1_1_net_1_1_sockets_1_1_socket.html',1,'Pcf::System::Net::Sockets']]],
  ['socket',['Socket',['../class_____o_s_1_1_core_api_1_1_socket.html',1,'__OS::CoreApi']]],
  ['socketaddress',['SocketAddress',['../class_pcf_1_1_system_1_1_net_1_1_socket_address.html',1,'Pcf::System::Net']]],
  ['socketexception',['SocketException',['../class_pcf_1_1_system_1_1_net_1_1_sockets_1_1_socket_exception.html',1,'Pcf::System::Net::Sockets']]],
  ['socketinformation',['SocketInformation',['../class_pcf_1_1_system_1_1_net_1_1_sockets_1_1_socket_information.html',1,'Pcf::System::Net::Sockets']]],
  ['solidbrush',['SolidBrush',['../class_pcf_1_1_system_1_1_drawing_1_1_solid_brush.html',1,'Pcf::System::Drawing']]],
  ['sorteddictionary',['SortedDictionary',['../class_pcf_1_1_system_1_1_collections_1_1_generic_1_1_sorted_dictionary.html',1,'Pcf::System::Collections::Generic']]],
  ['sorteddictionary_3c_20int32_5ft_2c_20t_20_3e',['SortedDictionary&lt; int32_t, T &gt;',['../class_pcf_1_1_system_1_1_collections_1_1_generic_1_1_sorted_dictionary.html',1,'Pcf::System::Collections::Generic']]],
  ['sorteddictionary_3c_20int64_5ft_2c_20pcf_3a_3asystem_3a_3astring_20_3e',['SortedDictionary&lt; int64_t, Pcf::System::String &gt;',['../class_pcf_1_1_system_1_1_collections_1_1_generic_1_1_sorted_dictionary.html',1,'Pcf::System::Collections::Generic']]],
  ['sorteddictionary_3c_20pcf_3a_3asystem_3a_3astring_2c_20serializationentry_20_3e',['SortedDictionary&lt; Pcf::System::String, SerializationEntry &gt;',['../class_pcf_1_1_system_1_1_collections_1_1_generic_1_1_sorted_dictionary.html',1,'Pcf::System::Collections::Generic']]],
  ['sorteddictionary_3c_20string_2c_20string_20_3e',['SortedDictionary&lt; String, String &gt;',['../class_pcf_1_1_system_1_1_collections_1_1_generic_1_1_sorted_dictionary.html',1,'Pcf::System::Collections::Generic']]],
  ['sortedset',['SortedSet',['../class_pcf_1_1_system_1_1_collections_1_1_generic_1_1_sorted_set.html',1,'Pcf::System::Collections::Generic']]],
  ['ssh_5fconn',['ssh_conn',['../structssh__conn.html',1,'']]],
  ['sshproto',['SSHPROTO',['../struct_s_s_h_p_r_o_t_o.html',1,'']]],
  ['ssl_5fconfig_5fdata',['ssl_config_data',['../structssl__config__data.html',1,'']]],
  ['ssl_5fconnect_5fdata',['ssl_connect_data',['../structssl__connect__data.html',1,'']]],
  ['stack',['Stack',['../class_pcf_1_1_system_1_1_collections_1_1_generic_1_1_stack.html',1,'Pcf::System::Collections::Generic']]],
  ['stackframe',['StackFrame',['../class_pcf_1_1_system_1_1_diagnostics_1_1_stack_frame.html',1,'Pcf::System::Diagnostics']]],
  ['stackoverflowexception',['StackOverflowException',['../class_pcf_1_1_system_1_1_stack_overflow_exception.html',1,'Pcf::System']]],
  ['stacktrace',['StackTrace',['../class_pcf_1_1_system_1_1_diagnostics_1_1_stack_trace.html',1,'Pcf::System::Diagnostics']]],
  ['standarderroroutput',['StandardErrorOutput',['../class_pcf_1_1_system_1_1_console_1_1_standard_error_output.html',1,'Pcf::System::Console']]],
  ['standardinput',['StandardInput',['../class_pcf_1_1_system_1_1_console_1_1_standard_input.html',1,'Pcf::System::Console']]],
  ['standardoutput',['StandardOutput',['../class_pcf_1_1_system_1_1_console_1_1_standard_output.html',1,'Pcf::System::Console']]],
  ['stat',['stat',['../structstat.html',1,'']]],
  ['static',['Static',['../struct_pcf_1_1_static.html',1,'Pcf']]],
  ['staticasserttypeeqhelper',['StaticAssertTypeEqHelper',['../structtesting_1_1internal_1_1_static_assert_type_eq_helper.html',1,'testing::internal']]],
  ['staticasserttypeeqhelper_3c_20t_2c_20t_20_3e',['StaticAssertTypeEqHelper&lt; T, T &gt;',['../structtesting_1_1internal_1_1_static_assert_type_eq_helper_3_01_t_00_01_t_01_4.html',1,'testing::internal']]],
  ['stopwatch',['Stopwatch',['../class_pcf_1_1_system_1_1_diagnostics_1_1_stopwatch.html',1,'Pcf::System::Diagnostics']]],
  ['stream',['Stream',['../class_pcf_1_1_system_1_1_i_o_1_1_stream.html',1,'Pcf::System::IO']]],
  ['streamreader',['StreamReader',['../class_pcf_1_1_system_1_1_i_o_1_1_stream_reader.html',1,'Pcf::System::IO']]],
  ['streamwriter',['StreamWriter',['../class_pcf_1_1_system_1_1_i_o_1_1_stream_writer.html',1,'Pcf::System::IO']]],
  ['string',['String',['../class_pcf_1_1_system_1_1_string.html',1,'Pcf::System']]],
  ['string',['String',['../classtesting_1_1internal_1_1_string.html',1,'testing::internal']]],
  ['stringbuilder',['StringBuilder',['../class_pcf_1_1_system_1_1_text_1_1_string_builder.html',1,'Pcf::System::Text']]],
  ['stringerfromobject',['StringerFromObject',['../struct_pcf_1_1_t_unit_1_1_expect_1_1_stringer_from_object.html',1,'Pcf::TUnit::Expect']]],
  ['stringerfromother',['StringerFromOther',['../struct_pcf_1_1_t_unit_1_1_expect_1_1_stringer_from_other.html',1,'Pcf::TUnit::Expect']]],
  ['stringformat',['StringFormat',['../class_pcf_1_1_system_1_1_drawing_1_1_string_format.html',1,'Pcf::System::Drawing']]],
  ['stringreader',['StringReader',['../class_pcf_1_1_system_1_1_i_o_1_1_string_reader.html',1,'Pcf::System::IO']]],
  ['stringwriter',['StringWriter',['../class_pcf_1_1_system_1_1_i_o_1_1_string_writer.html',1,'Pcf::System::IO']]],
  ['synchronizationlockexception',['SynchronizationLockException',['../class_pcf_1_1_system_1_1_threading_1_1_synchronization_lock_exception.html',1,'Pcf::System::Threading']]],
  ['synchronizedtextreader',['SynchronizedTextReader',['../class_pcf_1_1_system_1_1_i_o_1_1_synchronized_text_reader.html',1,'Pcf::System::IO']]],
  ['synchronizedtextwriter',['SynchronizedTextWriter',['../class_pcf_1_1_system_1_1_i_o_1_1_synchronized_text_writer.html',1,'Pcf::System::IO']]],
  ['systemcolors',['SystemColors',['../class_pcf_1_1_system_1_1_drawing_1_1_system_colors.html',1,'Pcf::System::Drawing']]],
  ['systemexception',['SystemException',['../class_pcf_1_1_system_1_1_system_exception.html',1,'Pcf::System']]],
  ['systeminformation',['SystemInformation',['../class_____o_s_1_1_forms_api_1_1_system_information.html',1,'__OS::FormsApi']]],
  ['systeminformation',['SystemInformation',['../class_pcf_1_1_system_1_1_windows_1_1_forms_1_1_system_information.html',1,'Pcf::System::Windows::Forms']]]
];
